// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetSecret provides a mock function for the type MockClient
func (_mock *MockClient) GetSecret(ctx context.Context, secretRef string) (map[string]string, error) {
	ret := _mock.Called(ctx, secretRef)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, secretRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, secretRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretRef string
func (_e *MockClient_Expecter) GetSecret(ctx interface{}, secretRef interface{}) *MockClient_GetSecret_Call {
	return &MockClient_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, secretRef)}
}

func (_c *MockClient_GetSecret_Call) Run(run func(ctx context.Context, secretRef string)) *MockClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetSecret_Call) Return(stringToString map[string]string, err error) *MockClient_GetSecret_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockClient_GetSecret_Call) RunAndReturn(run func(ctx context.Context, secretRef string) (map[string]string, error)) *MockClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretKey provides a mock function for the type MockClient
func (_mock *MockClient) GetSecretKey(ctx context.Context, secretRef string, key string) (string, error) {
	ret := _mock.Called(ctx, secretRef, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, secretRef, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, secretRef, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, secretRef, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetSecretKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretKey'
type MockClient_GetSecretKey_Call struct {
	*mock.Call
}

// GetSecretKey is a helper method to define mock.On call
//   - ctx context.Context
//   - secretRef string
//   - key string
func (_e *MockClient_Expecter) GetSecretKey(ctx interface{}, secretRef interface{}, key interface{}) *MockClient_GetSecretKey_Call {
	return &MockClient_GetSecretKey_Call{Call: _e.mock.On("GetSecretKey", ctx, secretRef, key)}
}

func (_c *MockClient_GetSecretKey_Call) Run(run func(ctx context.Context, secretRef string, key string)) *MockClient_GetSecretKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetSecretKey_Call) Return(s string, err error) *MockClient_GetSecretKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetSecretKey_Call) RunAndReturn(run func(ctx context.Context, secretRef string, key string) (string, error)) *MockClient_GetSecretKey_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockClient
func (_mock *MockClient) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockClient_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockClient_Expecter) Name() *MockClient_Name_Call {
	return &MockClient_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockClient_Name_Call) Run(run func()) *MockClient_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Name_Call) Return(s string) *MockClient_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_Name_Call) RunAndReturn(run func() string) *MockClient_Name_Call {
	_c.Call.Return(run)
	return _c
}
