// Package output handles formatting of environment variables for different output formats.
package output

import (
	"encoding/json"
	"fmt"
	"io"
	"slices"
	"strings"
	"time"

	"github.com/sentiolabs/envctl/internal/env"
)

// Format represents an output format type.
type Format string

const (
	// FormatEnv outputs KEY=VALUE format.
	FormatEnv Format = "env"
	// FormatShell outputs export KEY="VALUE" format.
	FormatShell Format = "shell"
	// FormatJSON outputs {"KEY": "VALUE"} format.
	FormatJSON Format = "json"
)

// ParseFormat parses a format string into a Format type.
func ParseFormat(s string) (Format, error) {
	switch strings.ToLower(s) {
	case "env", "":
		return FormatEnv, nil
	case "shell":
		return FormatShell, nil
	case "json":
		return FormatJSON, nil
	default:
		return "", fmt.Errorf("unknown format: %s (valid formats: env, shell, json)", s)
	}
}

// Write writes the entries in the specified format.
func Write(w io.Writer, entries []env.Entry, format Format) error {
	switch format {
	case FormatEnv:
		return writeEnvFormat(w, entries)
	case FormatShell:
		return writeShellFormat(w, entries)
	case FormatJSON:
		return writeJSONFormat(w, entries)
	default:
		return fmt.Errorf("unknown format: %s", format)
	}
}

// WriteEnvFile writes entries in .env file format with header comments.
// Header comments are non-critical; actual data errors are returned by writeEnvFormat.
//
//nolint:revive // Header comment writes to same writer; data writes check errors
func WriteEnvFile(w io.Writer, entries []env.Entry, envName string) error {
	// Write header comments
	fmt.Fprintf(w, "# Generated by envctl from environment: %s\n", envName)
	fmt.Fprintf(w, "# Timestamp: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintln(w, "# DO NOT COMMIT THIS FILE")
	fmt.Fprintln(w)

	return writeEnvFormat(w, entries)
}

// writeEnvFormat writes KEY=VALUE format.
func writeEnvFormat(w io.Writer, entries []env.Entry) error {
	sortedEntries := sortEntries(entries)

	for _, e := range sortedEntries {
		value := quoteValue(e.Value)
		if _, err := fmt.Fprintf(w, "%s=%s\n", e.Key, value); err != nil {
			return err
		}
	}
	return nil
}

// writeShellFormat writes export KEY="VALUE" format.
func writeShellFormat(w io.Writer, entries []env.Entry) error {
	sortedEntries := sortEntries(entries)

	for _, e := range sortedEntries {
		value := shellEscape(e.Value)
		if _, err := fmt.Fprintf(w, "export %s=%s\n", e.Key, value); err != nil {
			return err
		}
	}
	return nil
}

// writeJSONFormat writes {"KEY": "VALUE"} format.
func writeJSONFormat(w io.Writer, entries []env.Entry) error {
	m := make(map[string]string, len(entries))
	for _, e := range entries {
		m[e.Key] = e.Value
	}

	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	return encoder.Encode(m)
}

// sortEntries returns entries sorted by key.
func sortEntries(entries []env.Entry) []env.Entry {
	sorted := make([]env.Entry, len(entries))
	copy(sorted, entries)
	slices.SortFunc(sorted, func(a, b env.Entry) int {
		return strings.Compare(a.Key, b.Key)
	})
	return sorted
}

// quoteValue quotes a value for .env format if needed.
// The strings.Builder methods never return errors, so we ignore them.
//
//nolint:revive // strings.Builder Write methods always return nil error
func quoteValue(s string) string {
	// Check if quoting is needed
	needsQuotes := strings.ContainsAny(s, " \t\n\"'$`\\!#") ||
		strings.Contains(s, "=") ||
		s == ""

	if !needsQuotes {
		return s
	}

	// Use double quotes and escape special characters
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\', '$', '`':
			sb.WriteByte('\\')
			sb.WriteRune(r)
		case '\n':
			sb.WriteString("\\n")
		case '\r':
			sb.WriteString("\\r")
		case '\t':
			sb.WriteString("\\t")
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// shellEscape escapes a value for shell export format.
// The strings.Builder methods never return errors, so we ignore them.
//
//nolint:revive // strings.Builder Write methods always return nil error
func shellEscape(s string) string {
	// Always use double quotes for shell format for consistency
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\', '$', '`', '!':
			sb.WriteByte('\\')
			sb.WriteRune(r)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// WriteList writes key names and sources for the list command.
// Output is typically to stdout where writes always succeed.
//
//nolint:revive // Output is to stdout which doesn't fail
func WriteList(w io.Writer, entries []env.Entry, quiet bool) error {
	sortedEntries := sortEntries(entries)

	if quiet {
		for _, e := range sortedEntries {
			fmt.Fprintln(w, e.Key)
		}
		return nil
	}

	// Calculate max key length for alignment
	maxKeyLen := 0
	for _, e := range sortedEntries {
		if len(e.Key) > maxKeyLen {
			maxKeyLen = len(e.Key)
		}
	}

	for _, e := range sortedEntries {
		fmt.Fprintf(w, "%-*s  (from: %s)\n", maxKeyLen, e.Key, e.Source)
	}
	return nil
}
